from allspark.models import KnowledgeEntry


def get_tier1_knowledge() -> list[KnowledgeEntry]:
    return [
        KnowledgeEntry(
            id="agriculture/soil/preparation",
            category="agriculture", subcategory="soil", priority=1,
            title="土壤准备与改良",
            summary="短期生存后需要建立稳定食物来源。土壤准备是农业的基础：清除杂草、翻松土壤、添加有机质、调节酸碱度。",
            steps=[
                "选择向阳、排水良好的地块，面积以2m×3m起步",
                "清除杂草和石块，深翻20-30厘米",
                "加入腐叶土、草木灰或堆肥改善土壤结构",
                "用简易pH试纸测试酸碱度（6.0-7.0最佳）",
                "过酸加草木灰，过碱加松针/腐叶",
                "整平地面，做畦（高畦排水，低畦保水）",
            ],
            prerequisites=["土地", "工具（锄/铲）", "有机质来源"],
            warnings=[
                "不要在工业区或道路旁种植——土壤可能含重金属",
                "新鲜粪便必须堆肥6个月以上才能使用",
                "连续种植同一作物会导致土壤贫瘠，需轮作",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/crops/fast_growing",
            category="agriculture", subcategory="crops", priority=1,
            title="快速生长作物种植",
            summary="灾后最需要的是快速产出食物。推荐速生作物：萝卜（30天）、小白菜（25天）、生菜（30天）、豆芽（5-7天）。",
            steps=[
                "豆芽：绿豆/黄豆浸泡8小时，每天冲洗2次，5-7天收获，不需要阳光",
                "小白菜：撒播种子，覆土0.5cm，保持湿润，25天可采",
                "萝卜：点播，间距10cm，30-40天收获根茎",
                "生菜：撒播或育苗移栽，30天开始采外叶",
                "红薯：扦插藤蔓，60-90天可收块根，叶也可食用",
            ],
            prerequisites=["种子或种苗", "土壤", "水源"],
            warnings=[
                "豆芽生产需注意通风，密闭潮湿易滋生细菌",
                "不要食用发霉或变色的豆芽",
                "野生种子可能不适应当地气候，优先使用本地品种",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/preservation/drying",
            category="agriculture", subcategory="preservation", priority=1,
            title="食物干燥保存法",
            summary="干燥是最古老的食物保存方法。去除水分使微生物无法生长，可保存数月至数年。",
            steps=[
                "选择新鲜无损的食材，清洗擦干",
                "切薄片（3-5mm），越薄干燥越快",
                "日晒法：铺在干净网架上，阳光直射，每天翻面，2-5天",
                "烟熏法：在火堆上方搭建熏架，低温慢熏6-12小时",
                "判断干燥程度：对折不断裂、不渗水即为充分干燥",
                "密封保存：用布袋或密封容器，加入干燥剂（生石灰/稻壳灰）",
            ],
            prerequisites=["食材", "干燥环境或热源"],
            warnings=[
                "潮湿天气不适合日晒干燥",
                "干燥不彻底会导致霉变，宁可过干不可欠干",
                "烟熏温度不要超过60°C，否则会烤熟而非干燥",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="chemistry/soap/making",
            category="chemistry", subcategory="soap", priority=1,
            title="手工皂制作",
            summary="卫生是生存的关键。用油脂和碱（草木灰提取）制作肥皂，用于清洁身体和物品，预防疾病。",
            steps=[
                "收集草木灰（硬木灰最佳），装入带孔容器",
                "用热水缓慢淋过草木灰，收集滤出液（碱液）",
                "将碱液蒸发浓缩至原体积1/3（可用鸡蛋测试浮力）",
                "加热油脂至温热（动物油或植物油均可）",
                "缓慢将碱液倒入油脂中，持续搅拌至浓稠（trace状态）",
                "倒入模具，保温24-48小时，脱模后晾置4-6周",
            ],
            prerequisites=["油脂", "草木灰", "容器", "搅拌工具"],
            warnings=[
                "碱液具有强腐蚀性，避免接触皮肤和眼睛",
                "制作时保持通风，佩戴防护",
                "未充分皂化的肥皂可能灼伤皮肤，需充分晾置",
                "如皮肤接触碱液，立即用大量清水冲洗",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="chemistry/charcoal/production",
            category="chemistry", subcategory="charcoal", priority=1,
            title="木炭烧制",
            summary="木炭是重要的燃料和材料。燃烧温度比木柴高、烟少，可用于冶炼、过滤、医药。",
            steps=[
                "选择硬木（橡木、枣木等），截成相似长度",
                "在地上挖圆坑或堆成土窑，底部留通风口",
                "将木材竖直紧密排列，中间留点火通道",
                "覆盖湿土/泥巴，仅留顶部一个出烟口",
                "从底部点火，控制通风量使木材不完全燃烧",
                "持续8-24小时（视木材量），烟色由白变蓝再变清时封窑",
                "完全密封冷却24小时以上再开窑取炭",
            ],
            prerequisites=["硬木", "空地", "泥土"],
            warnings=[
                "烧炭过程产生一氧化碳，必须在室外进行",
                "不要在密闭空间或帐篷内烧炭——一氧化碳中毒致命",
                "封窑前确认不再有明火，否则开窑会复燃",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="mechanical/tools/blacksmithing_basic",
            category="mechanical", subcategory="tools", priority=1,
            title="基础锻造与工具修复",
            summary="金属工具是文明延续的关键。掌握基础锻造可以修复和制作刀、锄、钉等基本工具。",
            steps=[
                "搭建简易锻造炉：用泥巴/砖砌成炉膛，底部留进风口",
                "燃料使用木炭（温度可达1000°C以上）",
                "用风箱或电扇鼓风提升温度",
                "将铁件放入炉中加热至樱桃红色（约800°C）",
                "在砧铁上用锤锻打成型——先粗打再精修",
                "淬火：将热工件浸入水或油中快速冷却以增加硬度",
                "回火：重新加热至200-300°C后缓冷，消除脆性",
            ],
            prerequisites=["铁料", "木炭", "砧铁/替代品", "锤子", "火炉"],
            warnings=[
                "锻造温度极高，注意烫伤和火灾",
                "淬火时会产生蒸汽飞溅，保持距离",
                "回火温度过高会失去硬度，过低则仍有脆性",
                "废铁回收时注意区分铁和钢——钢能淬硬，铁不能",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="mechanical/rope_knots/essential",
            category="mechanical", subcategory="rope_knots", priority=1,
            title="生存必备绳结",
            summary="绳结是生存的基本技能。掌握6个核心绳结可以应对大部分场景：搭建、固定、救援、捆绑。",
            steps=[
                "称人结（Bowline）：制作固定环，不会滑动，救援用",
                "双套结（Clove Hitch）：将绳固定在柱/杆上，可调节",
                "八字结（Figure-8）：防滑止结，攀爬和安全用",
                "方回结（Square Lashing）：交叉杆固定，搭建框架用",
                "渔人结（Fisherman's Bend）：连接两根绳子",
                "营钉结（Taut-line Hitch）：可调节松紧的固定结，帐篷用",
            ],
            prerequisites=["绳索"],
            warnings=[
                "绳结在潮湿时可能滑动，关键部位使用双重结",
                "定期检查绳结是否松动",
                "救援时绳索承重不超过破断力的1/5",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="weather/observation/basics",
            category="weather", subcategory="observation", priority=1,
            title="天气观测基础",
            summary="无天气预报时，通过自然现象预测天气变化，对生存决策至关重要。",
            steps=[
                "看云：积雨云（高耸如花椰菜）→雷暴将至；卷云（丝状高空）→天气变化1-2天",
                "看风：风向突变通常伴随天气变化；山谷中白天风上山、夜间风下山为正常",
                "看动物：燕子低飞→即将下雨；蚂蚁搬家→大雨将至；蜜蜂归巢→天气转坏",
                "看天空：红霞朝出→风雨将至；红霞晚出→天气晴好",
                "感受：关节疼痛、湿度骤增→可能下雨；空气闷热无风→雷暴前兆",
                "记录：每天记录天气，一周后可发现本地规律",
            ],
            prerequisites=["观察力", "记录工具"],
            warnings=[
                "山区天气变化极快，不要只看当前天气做远行决定",
                "雷暴时远离高地、孤立大树和水面",
                "洪涝风险区域注意上游天气",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="energy/fire/charcoal_gasifier",
            category="energy", subcategory="fire", priority=1,
            title="简易木炭气化炉",
            summary="木炭气化炉可以将木柴不完全燃烧产生可燃气，用于烹饪和供暖，效率比直接燃烧高2-3倍。",
            steps=[
                "准备两个金属桶（大桶套小桶）",
                "小桶底部和侧面打孔（直径1cm，间隔5cm）",
                "小桶内放入木柴/木炭，从顶部点火",
                "大桶底部开进风口，顶部接烟管",
                "燃烧产生的气体从烟管导出可二次燃烧",
                "调节进风口大小控制火力",
            ],
            prerequisites=["两个金属桶", "工具", "木柴/木炭"],
            warnings=[
                "气化炉产生一氧化碳，必须在通风处使用",
                "炉体温度极高，周围不得有易燃物",
                "定期清理灰烬保持气流畅通",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="energy/solar/thermal_basic",
            category="energy", subcategory="solar", priority=1,
            title="太阳能热利用基础",
            summary="太阳能是最可靠的能源。不需要复杂设备即可利用太阳能加热水、干燥食物、烹饪。",
            steps=[
                "太阳能热水器：黑色容器（涂黑的水桶/管道）放在阳光直射处，可加热水至60°C",
                "太阳灶：用铝箔/镜面制作抛物面反射器，焦点温度可达200°C",
                "太阳能干燥：透明塑料棚+通风，加速食物干燥",
                "太阳能蒸馏：塑料膜覆盖盐水容器，冷凝水滴入收集槽",
                "最佳使用时间：上午10点至下午3点",
            ],
            prerequisites=["黑色容器/反射材料", "阳光"],
            warnings=[
                "太阳灶焦点温度极高，注意烫伤和火灾",
                "阴天和冬季太阳能效率大幅降低",
                "太阳能蒸馏产水量有限，仅作补充水源",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
    ]


def get_tier2_knowledge() -> list[KnowledgeEntry]:
    return [
        KnowledgeEntry(
            id="agriculture/composting/system",
            category="agriculture", subcategory="composting", priority=2,
            title="堆肥系统建设",
            summary="持续农业需要持续补充土壤养分。堆肥将有机废物转化为优质肥料，是自给农业的基石。",
            steps=[
                "选择阴凉通风处，搭建1m×1m×1m的堆肥箱（木条/竹竿/砖）",
                "分层堆放：棕色层（干叶/稻草/纸）→绿色层（菜叶/草/粪便）→薄土层",
                "棕色:绿色比例约3:1，保持湿润但不积水",
                "每1-2周翻堆一次，引入空气加速分解",
                "堆内温度应达到55-65°C（手插入感觉温热）",
                "2-6个月完成，成品为深褐色松散泥土状",
            ],
            prerequisites=["有机废物", "堆肥空间", "翻堆工具"],
            warnings=[
                "不要放入肉类、油脂、病株——会招虫和传播病害",
                "堆肥温度不足55°C无法杀灭病原体和杂草种子",
                "猫狗粪便可能含寄生虫，不建议使用",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/seed_saving/techniques",
            category="agriculture", subcategory="seed_saving", priority=2,
            title="种子保存技术",
            summary="种子是农业的命脉。掌握种子保存技术可以持续种植，不必依赖外部种子供应。",
            steps=[
                "选择最健壮的植株留种，标记不要误采",
                "等果实完全成熟再采收种子",
                "湿种子（番茄/黄瓜）：取出后水洗去果肉，晾干",
                "干种子（豆类/谷物）：连荚/穗晾干后脱粒",
                "干燥处理：阴凉通风处晾7-14天至含水量8%以下",
                "储存：纸袋或密封罐，加入干燥剂，存于阴凉干燥处",
                "标注品种、日期、来源",
            ],
            prerequisites=["成熟作物", "干燥空间", "储存容器"],
            warnings=[
                "杂交种子（F1）后代性状分离，优先保存自交品种",
                "种子含水量过高会导致霉变",
                "不同品种的十字花科植物会互相杂交，需隔离种植",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="chemistry/paper/making",
            category="chemistry", subcategory="paper", priority=2,
            title="手工造纸",
            summary="纸张是记录和传播知识的基础。用植物纤维制作纸张，延续文明的记忆。",
            steps=[
                "收集纤维原料：旧纸/稻草/麻/树皮（构树皮最佳）",
                "将原料浸泡1-2天软化",
                "用碱液（草木灰水）煮沸2-4小时分解木质素",
                "充分水洗去除碱液",
                "用锤/石臼捣碎成纸浆",
                "纸浆加水稀释，加入粘合剂（黄蜀葵/淀粉糊）",
                "用抄纸框（木框+细网）抄纸——水平浸入再提起",
                "覆在平板上压水、晾干",
            ],
            prerequisites=["植物纤维", "草木灰", "抄纸框", "大量水"],
            warnings=[
                "碱液煮沸时注意通风和防护",
                "纸浆浓度影响纸张厚度——稀则薄、浓则厚",
                "干燥时避免阳光直射，防止纸张翘曲",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="chemistry/dye/natural",
            category="chemistry", subcategory="dye", priority=2,
            title="天然染料提取",
            summary="天然染料用于染色和标记。不同植物可提取不同颜色：蓝靛（蓝色）、茜草（红色）、黄柏（黄色）。",
            steps=[
                "蓝色：蓝草（板蓝根/蓼蓝）叶浸泡发酵，加碱液制靛蓝",
                "红色：茜草根切碎，热水浸泡提取茜素",
                "黄色：黄柏皮/石榴皮/洋葱皮热水煮提取",
                "黑色：五倍子（虫瘿）加铁媒染剂",
                "媒染剂：明矾（铝媒）、铁锈水（铁媒）、草木灰（碱媒）",
                "染色流程：媒染→水洗→浸染→水洗→晾干",
            ],
            prerequisites=["染料植物", "媒染剂", "水", "容器"],
            warnings=[
                "某些染料植物有毒，操作后洗手",
                "铁媒染剂会使颜色变暗，注意用量",
                "天然染色色牢度不如化学染料，需要多次浸染加深",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="mechanical/watermill/simple",
            category="mechanical", subcategory="watermill", priority=2,
            title="简易水力磨坊",
            summary="利用水流动力研磨谷物、锯木。水力是可持续的机械动力来源。",
            steps=[
                "选址：水流稳定、落差0.5-2m的溪流",
                "制作水轮：用木板制作直径1-2m的轮子，边缘装水斗",
                "安装水轮：水平轴安装，水斗朝向水流方向",
                "连接磨石：水轮轴通过齿轮连接上磨石",
                "调整水流：用导流槽将水引向水轮顶部",
                "维护：定期检查轴承润滑和木件腐朽",
            ],
            prerequisites=["溪流", "木材", "石磨", "基本木工技能"],
            warnings=[
                "洪水可能冲毁水轮，雨季注意加固",
                "木制轴承需要经常润滑（动物油脂/石墨）",
                "磨石碎裂有飞出危险，周围设防护",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="mechanical/bicycle_generator",
            category="mechanical", subcategory="generator", priority=2,
            title="自行车发电装置",
            summary="用废旧自行车和发电机改装成人力发电装置，可为小电器充电和照明。",
            steps=[
                "获取废旧自行车和直流发电机/汽车发电机",
                "将发电机固定在自行车后轮旁",
                "用皮带或摩擦轮连接后轮和发电机",
                "连接整流器和稳压电路（12V系统）",
                "接蓄电池储存电能（铅酸电池最易获取）",
                "骑行发电：中等速度可输出50-100W功率",
            ],
            prerequisites=["自行车", "发电机", "整流器", "蓄电池", "基本电路知识"],
            warnings=[
                "发电机电压不稳定，必须接稳压器后再接设备",
                "铅酸电池充电时产生氢气，保持通风远离明火",
                "长时间骑行发电非常消耗体力，不适合体弱者",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="weather/shelter/climate_design",
            category="weather", subcategory="shelter", priority=2,
            title="气候适应性庇护所设计",
            summary="长期定居需要根据当地气候设计庇护所。不同气候需要不同的保温、通风、防水策略。",
            steps=[
                "寒冷地区：厚墙（土/石/草泥）、小窗朝南、双层屋顶保温、地暖烟道",
                "炎热潮湿：高脚屋防潮、大屋檐遮阳、交叉通风、竹/木结构",
                "炎热干燥：厚土墙蓄热、小窗减少热辐射、内院式布局、地下储藏室",
                "多雨地区：陡坡屋顶、深屋檐、防潮层、排水沟渠",
                "台风地区：低矮结构、加固绑扎、背风选址",
            ],
            prerequisites=["当地气候数据", "建筑材料", "工具"],
            warnings=[
                "选址避开洪水线、滑坡体和风口",
                "烟道/壁炉必须正确排烟——一氧化碳无声致命",
                "土坯建筑在地震带需要加固（竹筋/木框架）",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="energy/wind/basic_turbine",
            category="energy", subcategory="wind", priority=2,
            title="简易风力发电",
            summary="风力是可持续能源。用简单材料制作小型风力发电机，为照明和通讯供电。",
            steps=[
                "选址：开阔高地，年平均风速4m/s以上",
                "制作叶片：PVC管剖开/木板/金属板，3叶片设计",
                "制作轮毂：金属圆盘固定叶片，中心连接发电机轴",
                "发电机：永磁直流电机（废旧汽车/自行车电机）",
                "塔架：4-6米高钢管/木杆，用拉索固定",
                "电气：整流器→稳压器→蓄电池→逆变器（如需交流）",
                "维护：定期检查叶片、轴承和电气连接",
            ],
            prerequisites=["发电机", "叶片材料", "塔架", "整流稳压电路"],
            warnings=[
                "风力发电机塔架必须牢固固定——倒塌致命",
                "雷暴时断开电气连接防止雷击",
                "旋转叶片有切割危险，设置安全距离",
                "风速超过设计极限时必须刹车或放倒叶片",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="energy/biogas/digester",
            category="energy", subcategory="biogas", priority=2,
            title="沼气池建设",
            summary="沼气是有机废物厌氧发酵产生的可燃气体。同时产出沼液沼渣作为优质肥料，一举两得。",
            steps=[
                "选址：靠近畜舍/厕所，地下水位低处",
                "建池：砖/石砌6-10m³圆筒形池，分进料间、发酵间、储气间",
                "密封：内壁用水泥砂浆抹面3遍，确保不漏气不漏水",
                "投料：人畜粪便+秸秆碎+水，干物质浓度8-10%",
                "启动：加入老沼液或牛粪作为菌种，密封发酵",
                "产气：7-15天开始产气，火焰呈蓝色为合格",
                "日常：每天加料，定期出渣，保持pH 6.8-7.5",
            ],
            prerequisites=["建池材料（砖/水泥）", "有机废物", "劳动力"],
            warnings=[
                "沼气含甲烷和硫化氢，有窒息和爆炸风险",
                "严禁在沼气池旁吸烟或使用明火",
                "下池检修必须先通风，多人监护——沼气池内缺氧致命",
                "冬季低温产气量下降，需保温措施",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="medicine/herbal/common",
            category="medicine", subcategory="herbal", priority=2,
            title="常见草药识别与应用",
            summary="药物短缺时，常见草药可处理基础病症。但必须准确识别，误用可能致命。",
            steps=[
                "退烧：柴胡（根煮水）、薄荷（叶泡茶）",
                "止血：三七（粉末外敷）、白及（粉末撒伤口）",
                "消炎：金银花（花泡水）、蒲公英（全草煮水）",
                "止泻：石榴皮（煮水）、车前草（叶煮水）",
                "驱虫：艾草（烟熏/泡水）、大蒜（生食）",
                "镇痛：延胡索（根煮水）、川芎（根煮水）",
            ],
            prerequisites=["草药识别能力", "参考图鉴"],
            warnings=[
                "绝对不要使用无法100%确认的植物——误食毒草可致命",
                "草药剂量难以精确控制，从小剂量开始",
                "孕妇、儿童、体弱者慎用草药",
                "草药不能替代专业医疗，仅作应急使用",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
    ]
