from allspark.models import KnowledgeEntry


def get_tier3_knowledge() -> list[KnowledgeEntry]:
    return [
        KnowledgeEntry(
            id="community/governance/structure",
            category="community", subcategory="governance", priority=2,
            title="社区组织架构设计",
            summary="长期生存需要建立稳定的社区组织。根据人数和技能分布，设计合理的权力结构和分工体系。火种可以辅助评估和推荐架构。",
            steps=[
                "统计社区人数、技能分布、健康状况",
                "10人以下：扁平结构，指挥官+执行者",
                "10-30人：增设领域专家（医疗/工程/农业/防卫）",
                "30人以上：分组管理，设立中层协调者",
                "超过50人：建议议事会制度，重大决策投票",
                "火种根据实时数据动态评估架构合理性",
            ],
            prerequisites=["社区成员登记", "技能评估", "火种系统"],
            warnings=[
                "权力过度集中会导致决策失误和群体不满",
                "完全民主在危机中效率过低，需要平衡",
                "定期（每2-4周）评估架构是否需要调整",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="community/conflict/resolution",
            category="community", subcategory="conflict", priority=2,
            title="冲突调解与仲裁",
            summary="多人共处必然产生冲突。建立系统化的冲突解决机制，避免矛盾升级影响群体生存。",
            steps=[
                "识别冲突类型：资源分配/权力争端/人际矛盾/价值观分歧",
                "资源冲突：按生存优先级分配，火种提供客观数据",
                "权力冲突：回归职责定义，指挥官最终裁定",
                "人际矛盾：第三方调解，必要时物理隔离",
                "价值观分歧：求同存异，以生存为共同底线",
                "记录每次冲突及解决方案，供未来参考",
            ],
            prerequisites=["社区规则", "调解人", "火种辅助"],
            warnings=[
                "忽视小冲突会导致大爆发",
                "调解人必须中立，不能是冲突当事方",
                "火种的建议是参考，不是命令",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="community/education/system",
            category="community", subcategory="education", priority=2,
            title="知识传承与教育体系",
            summary="文明延续依赖知识传承。建立系统化的教育体系，确保关键技能不会因人员损失而失传。",
            steps=[
                "盘点社区关键技能和知识持有者",
                "每个关键技能至少培养2名传承人",
                "建立师徒制：专家带教，实践为主",
                "火种知识库作为标准化教材和考核基准",
                "定期考核：每季度评估技能掌握程度",
                "记录学习进度和考核结果到火种系统",
            ],
            prerequisites=["技能清单", "知识库", "教学时间"],
            warnings=[
                "不要让任何关键技能只掌握在一个人手中",
                "理论必须配合实践，纸上谈兵在灾难中致命",
                "儿童教育不能中断，他们是文明的未来",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="engineering/blacksmithing/basics",
            category="engineering", subcategory="blacksmithing", priority=2,
            title="基础锻造技术",
            summary="金属加工是文明重建的核心技能。从简易锻造炉开始，逐步掌握基础锻造技术，制作工具和零件。",
            steps=[
                "搭建简易锻造炉：耐火砖/泥砖围成炉膛，连接手拉风箱",
                "燃料：木炭（硬木烧制，比煤炭更易获得）",
                "工具：铁锤、铁钳（可从废墟获取）",
                "加热钢铁至橙红色（约900°C），开始锻造",
                "基本操作：延伸（拉长）、镦粗（压短）、弯曲、冲孔",
                "淬火：烧红后迅速浸入水或油中增加硬度",
                "回火：淬火后低温加热（200-400°C）消除脆性",
            ],
            prerequisites=["耐火材料", "木炭/燃料", "铁锤铁钳", "废钢材"],
            warnings=[
                "锻造温度极高，必须做好防护（厚手套、护目镜）",
                "淬火不当会导致工件开裂，需要反复练习",
                "通风不良会导致一氧化碳中毒",
                "废钢材成分不明，性能可能不稳定",
            ],
            verification="field_tested",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="engineering/electricity/generator",
            category="engineering", subcategory="electricity", priority=2,
            title="简易发电装置",
            summary="电力是现代文明的基础。利用现有材料搭建简易发电装置，为火种和关键设备供电。",
            steps=[
                "方案一：自行车发电机——改装自行车后轮连接汽车发电机，人力踩踏发电，约50-100W",
                "方案二：水力发电——利用溪流落差，自制水轮带动发电机，功率取决于水流",
                "方案三：风力发电——自制叶片+汽车发电机，需要稳定风力区域",
                "方案四：蒸汽发电——锅炉+蒸汽轮机，技术复杂但功率大",
                "储能：铅酸电池（汽车电瓶）存储电能",
                "调压：使用稳压电路保护设备",
            ],
            prerequisites=["发电机（汽车发电机可用）", "电池", "导线", "基本电子知识"],
            warnings=[
                "电力系统必须做好绝缘和防护，触电致命",
                "铅酸电池充电时会产生氢气，必须通风",
                "不要短路电池，会引发火灾或爆炸",
                "优先保障火种系统供电",
            ],
            verification="field_tested",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="engineering/electricity/wiring",
            category="engineering", subcategory="electricity", priority=2,
            title="基础电路搭建",
            summary="从零搭建简易电路系统，包括线路规划、安全保护和基本维修。",
            steps=[
                "规划电路：照明线路（12V LED）、充电线路、设备线路分开",
                "选择导线：铜线最佳，铝线次之，截面积根据电流选择",
                "连接方式：绞接+绝缘胶布，有条件用焊接",
                "保护：每条线路安装保险丝（可自制：细铜丝）",
                "开关：简易刀闸开关，控制通断",
                "接地：将金属外壳接入大地，防止触电",
            ],
            prerequisites=["导线", "绝缘材料", "基本工具", "万用表（如有）"],
            warnings=[
                "裸露导线必须绝缘处理，防止短路和触电",
                "不要超负荷使用导线，会过热起火",
                "湿手不要触碰电气设备",
                "维修前必须断电",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="engineering/masonry/basics",
            category="engineering", subcategory="masonry", priority=2,
            title="基础砌筑与建筑",
            summary="长期定居需要永久性建筑。掌握基础砌筑技术，建造坚固的住所和设施。",
            steps=[
                "材料：就地取材——石材、砖块、夯土、竹木",
                "基础：挖掘地基深30-50cm，填碎石夯实",
                "砂浆：水泥+沙+水（1:3:0.5）；无水泥用石灰砂浆或泥浆",
                "砌墙：错缝搭接，每层水平，角部加固",
                "门窗：预留洞口，上方加过梁（木梁或角钢）",
                "屋顶：人字形或平顶，根据降雨量选择",
            ],
            prerequisites=["建材", "工具（瓦刀、水平尺）", "劳动力"],
            warnings=[
                "地基不牢会导致墙体开裂甚至倒塌",
                "承重墙不能随意开洞",
                "地震区必须增加圈梁和构造柱",
                "高处作业注意安全，防止坠落",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/livestock/chicken",
            category="agriculture", subcategory="livestock", priority=2,
            title="家禽养殖——鸡",
            summary="鸡是最容易养殖的家禽，提供蛋和肉。管理简单，繁殖快，适合社区养殖。",
            steps=[
                "鸡舍：每只鸡需0.3-0.5㎡空间，通风良好，防雨防寒",
                "栖架：离地50-80cm，每只鸡20cm栖位",
                "产蛋箱：每3-4只鸡一个，铺稻草",
                "饲料：谷物+菜叶+虫子+矿物质（蛋壳粉补钙）",
                "饮水：清洁饮水不断，每天更换",
                "孵化：自然孵化（母鸡抱窝）21天出雏",
                "防疫：保持鸡舍干燥清洁，隔离病鸡",
            ],
            prerequisites=["鸡舍", "种鸡（1公:8-10母）", "饲料来源"],
            warnings=[
                "禽流感：接触病鸡后必须洗手消毒",
                "黄鼠狼/蛇/野猫是主要天敌，做好防护",
                "不要给鸡喂发霉饲料",
                "新引入的鸡必须隔离观察一周",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/livestock/goat",
            category="agriculture", subcategory="livestock", priority=2,
            title="山羊养殖",
            summary="山羊适应性强，提供奶、肉和皮毛。是灾后重要的蛋白质和营养来源。",
            steps=[
                "圈舍：干燥通风，每只成年羊需1.5-2㎡",
                "放牧：每天放牧4-6小时，注意避开有毒植物",
                "补饲：干草+精料（玉米、豆粕），产奶期增加营养",
                "饮水：每天2-3次清洁饮水",
                "繁殖：8-10月龄性成熟，孕期150天，通常产1-2羔",
                "挤奶：每天早晚各一次，注意卫生",
                "防疫：定期驱虫，保持圈舍清洁",
            ],
            prerequisites=["圈舍", "种羊", "牧草或饲料", "水源"],
            warnings=[
                "山羊啃食树皮，注意保护林木",
                "圈舍潮湿会导致蹄病",
                "新购入羊只必须隔离检疫",
                "山羊奶需煮沸后饮用",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="agriculture/aquaculture/fish_pond",
            category="agriculture", subcategory="aquaculture", priority=2,
            title="简易鱼塘养殖",
            summary="鱼塘提供稳定的蛋白质来源。利用天然水源或雨水建造简易鱼塘，养殖淡水鱼。",
            steps=[
                "选址：水源充足、地势低洼、土质黏性好的地方",
                "建塘：面积100-500㎡，深1.5-2m，坡度1:1.5",
                "防渗：夯实塘底，黏土铺底或塑料膜防渗",
                "清塘：生石灰75kg/亩消毒，7天后放水",
                "鱼种：鲤鱼、鲫鱼、草鱼混养（比例4:3:3）",
                "投喂：每天2次，投喂量为鱼体重3-5%",
                "管理：定期换水1/3，监测水质（透明度30-40cm）",
            ],
            prerequisites=["水源", "土地", "鱼苗", "饲料"],
            warnings=[
                "鱼塘不能建在污染源下游",
                "高温天气注意增氧，防止泛塘",
                "暴雨时注意防逃，加固塘埂",
                "不要过量投喂，残饵会败坏水质",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="medicine/herbal/pharmacopoeia",
            category="medicine", subcategory="herbal", priority=2,
            title="常见药用植物手册",
            summary="现代药物耗尽后，传统草药是主要治疗手段。掌握常见药用植物的识别、采集和使用方法。",
            steps=[
                "退烧：金银花（忍冬）花/叶煎服，每日10-15g",
                "止血：三七粉外敷，或艾叶捣烂敷伤口",
                "消炎：蒲公英全草煎服，或鲜叶捣烂外敷",
                "止泻：石榴皮煎服，或茶叶浓煎",
                "止咳：枇杷叶（去毛）煎服，或川贝炖梨",
                "解毒：绿豆甘草汤（绿豆50g+甘草10g煎服）",
                "外伤：紫草油（紫草浸泡植物油）涂抹",
            ],
            prerequisites=["植物识别能力", "煎药器具", "干燥储存条件"],
            warnings=[
                "必须100%确认植物种类再使用，误食有毒植物可致命",
                "孕妇禁用多数草药，特别是活血化瘀类",
                "草药剂量不精确，从小剂量开始",
                "严重疾病优先寻求专业医疗",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="medicine/surgery/basic",
            category="medicine", subcategory="surgery", priority=2,
            title="紧急外科基础",
            summary="当无法获得专业医疗时，部分外科操作必须由非专业人员执行。这是最后手段，仅在其他选择都不存在时使用。",
            steps=[
                "清创术：用煮沸盐水冲洗伤口，去除异物和坏死组织",
                "缝合：用煮沸消毒的针线，间断缝合，间距1cm",
                "拔牙：松动牙齿用消毒钳左右摇动后拔出，咬棉球止血",
                "脓肿切开：消毒后用消毒刀片切开，引流脓液",
                "骨折固定：夹板+绷带，固定上下两个关节",
                "烧伤处理：冷水冲洗20分钟，不要挑破水泡，无菌包扎",
            ],
            prerequisites=["消毒器具", "纱布绷带", "基本药物", "助手"],
            warnings=[
                "这是最后手段，任何可能获得专业医疗的情况都应优先",
                "所有器具必须严格消毒（煮沸15分钟以上）",
                "术后密切观察感染迹象：红肿、发热、化脓",
                "记录所有操作，供后续医疗参考",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="communication/radio/ham",
            category="communication", subcategory="radio", priority=2,
            title="业余无线电通信",
            summary="无线电是远距离通信的唯一可靠手段。建立业余电台，与外界保持联系。",
            steps=[
                "设备：短波电台（3-30MHz），可用废旧收音机改装",
                "天线：偶极天线最简单——两根1/4波长导线，中间接馈线",
                "电源：12V电池或手摇发电机",
                "频率：40m波段（7.000-7.200MHz）白天，80m波段（3.500-3.900MHz）夜间",
                "通信方式：莫尔斯电码（最省电）或语音（AM/SSB）",
                "呼号：自编临时呼号，格式：区域代码+序号",
                "协议：每次通信记录时间、频率、对方呼号、内容摘要",
            ],
            prerequisites=["短波电台", "天线材料", "电源", "莫尔斯码表"],
            warnings=[
                "发射大功率信号可能暴露位置，谨慎使用",
                "雷雨天气必须断开天线，防止雷击",
                "不要发射虚假求救信号",
                "遵守基本通信礼仪，避免干扰紧急频率",
            ],
            verification="field_tested",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="communication/morse/code",
            category="communication", subcategory="morse", priority=2,
            title="莫尔斯电码速查",
            summary="莫尔斯电码是最基本的远距离通信编码，只需简单设备即可发送。SOS是国际通用求救信号。",
            steps=[
                "基本规则：点（.）短按，划（-）长按（3倍点时长）",
                "SOS：··· ——— ···（三短三长三短）",
                "常用字母：A·- B-··· C-·-· D-·· E· F··-· G--· H···· I·· J·--- K-·- L·-·· M-- N-· O--- P·--· Q--·- R·-· S··· T- U··- V···- W·-- X-··- Y-·-- Z--··",
                "数字：1·---- 2··--- 3···-- 4····- 5····· 6-···· 7--··· 8---·· 9----· 0-----",
                "发送技巧：先发呼号，再发对方呼号，然后内容",
                "光信号：手电筒/反光镜，短闪=点，长闪=划",
                "声音信号：短敲=点，长敲=划",
            ],
            prerequisites=["信号发送设备（手电筒/哨子/电键）"],
            warnings=[
                "SOS仅用于真正紧急情况",
                "发送前先监听频率，避免干扰他人",
                "练习时不要在紧急频率上发送",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="defense/perimeter/design",
            category="defense", subcategory="perimeter", priority=2,
            title="社区防御体系设计",
            summary="长期定居点需要系统化的防御体系。从预警到拒止，建立多层防御。",
            steps=[
                "外层预警：外围500m设置绊线警报（细线+铃铛/罐头）",
                "观察哨：制高点设置24小时值班观察点",
                "屏障层：围栏/篱笆/壕沟，高度2m以上",
                "入口控制：单一出入口，设岗哨和身份验证",
                "内层防御：核心区域（物资库/医疗站）额外加固",
                "逃生路线：至少规划2条不同方向的撤离路线",
                "火种辅助：监控传感器数据，异常自动预警",
            ],
            prerequisites=["围栏材料", "劳动力", "观察哨位", "火种系统"],
            warnings=[
                "防御体系不能完全依赖物理屏障，人的警觉最重要",
                "定期演练防御预案，确保所有人熟悉流程",
                "避免过度军事化导致社区氛围紧张",
                "火种预警是辅助，不能替代人工巡逻",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="civilization/record/archives",
            category="civilization", subcategory="record", priority=3,
            title="文明档案记录",
            summary="记录和保存人类文明知识是火种的核心使命之一。建立系统化的档案记录体系。",
            steps=[
                "分类：科学/技术/医学/农业/历史/文化/法律/艺术",
                "载体：纸质（最持久）+ 数字（火种存储）+ 口头传承",
                "书写：使用碳素墨水或铅笔，避免可擦写笔",
                "纸张：优质无酸纸，干燥密封保存",
                "数字化：火种知识库为标准格式，定期备份到SKF",
                "更新：每季度审核档案完整性，补充缺失内容",
                "传承：关键知识必须有多人掌握+多载体存储",
            ],
            prerequisites=["书写材料", "存储空间", "火种系统"],
            warnings=[
                "纸质档案怕火怕水，存储位置必须安全",
                "不要只依赖数字存储，电磁脉冲/硬件故障可能导致丢失",
                "口头传承会随代际衰减，必须配合文字记录",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
        KnowledgeEntry(
            id="civilization/law/basic",
            category="civilization", subcategory="law", priority=3,
            title="社区基本法规框架",
            summary="长期社区需要基本法律框架维持秩序。从最基本的生存规则开始，逐步完善。",
            steps=[
                "第一条：生存优先——任何行动不得危及群体基本生存",
                "第二条：资源共享——基本生存资源（水/食物/医疗）按需分配",
                "第三条：劳动义务——有劳动能力者必须参与社区工作",
                "第四条：禁止暴力——内部暴力零容忍，争端通过调解解决",
                "第五条：知识共享——个人掌握的生存知识必须传授给他人",
                "第六条：指挥权——指挥官在紧急状况下有临时决定权",
                "第七条：申诉权——任何成员可对决定提出申诉",
                "修改：法规修改需2/3以上成员同意",
            ],
            prerequisites=["社区成员", "火种记录系统"],
            warnings=[
                "法规必须得到大多数成员认可，否则形同虚设",
                "执法必须公正，否则比无法规更糟",
                "法规应随社区发展定期修订",
                "火种可以记录和提醒法规，但不能强制执行",
            ],
            verification="expert_verified",
            source="pre_collapse",
        ),
    ]
